// api/seo/strategy/exportPageOptimization.js
//
// STEP 7.5 — Export On-Page Blueprint (Excel)
//
// HARD RULES:
// - Export ONLY if strategy/pageOptimization.locked === true
// - Read Firestore only; do not modify anything
// - No AI, no OpenAI, no regeneration

import admin from "../../firebaseAdmin";
import XLSX from "xlsx";

// -------------------- AUTH --------------------
async function getUidFromRequest(req) {
  const authHeader = req.headers.authorization || "";
  const match = authHeader.match(/^Bearer (.+)$/);
  if (!match) throw new Error("Missing Authorization Bearer token.");
  const idToken = match[1];
  const decoded = await admin.auth().verifyIdToken(idToken);
  return decoded.uid;
}

// -------------------- EFFECTIVE CONTEXT --------------------
async function resolveEffectiveContext(uid, websiteId) {
  const ref = admin.firestore().doc(`users/${uid}/websites/${websiteId}`);
  const snap = await ref.get();

  if (!snap.exists) {
    return { effectiveUid: uid, effectiveWebsiteId: websiteId };
  }

  const w = snap.data() || {};
  const effectiveUid = w.ownerUid || uid;
  const effectiveWebsiteId = w.ownerWebsiteId || websiteId;

  return { effectiveUid, effectiveWebsiteId };
}

// -------------------- HELPERS --------------------
function safeStr(x) {
  return String(x || "").trim();
}

function normalizeSecondaryKeywords(v) {
  if (!Array.isArray(v)) return "";
  const arr = v
    .map((x) => (typeof x === "string" ? x : x?.keyword))
    .filter(Boolean)
    .map((s) => String(s).trim())
    .filter(Boolean);
  return arr.join(", ");
}

function normalizeH2Structure(v) {
  if (Array.isArray(v)) {
    return v.map((s) => safeStr(s)).filter(Boolean).join(" | ");
  }
  // sometimes could be a single string
  const s = safeStr(v);
  return s ? s : "";
}

function normalizeContentBlocks(v) {
  if (!Array.isArray(v) || v.length === 0) return "";
  // Format: "Block Title – Description" | "Block Title – Description"
  const parts = [];
  for (const b of v) {
    const heading = safeStr(b?.heading);
    const purpose = safeStr(b?.purpose);
    if (!heading && !purpose) continue;
    if (heading && purpose) parts.push(`${heading} – ${purpose}`);
    else parts.push(heading || purpose);
  }
  return parts.join(" | ");
}

function normalizeSchemaAccepted(v) {
  if (!Array.isArray(v) || v.length === 0) return "None";
  const accepted = v
    .filter((s) => safeStr(s?.status).toLowerCase() === "accepted")
    .map((s) => safeStr(s?.type))
    .filter(Boolean);
  return accepted.length ? accepted.join(", ") : "None";
}

function normalizeInternalLinks(v) {
  if (!Array.isArray(v) || v.length === 0) return "";
  const parts = [];
  for (const x of v) {
    const a = safeStr(x?.anchorText);
    const u = safeStr(x?.targetUrl);
    if (!a || !u) continue;
    parts.push(`${a} → ${u}`);
  }
  return parts.join(" | ");
}

function normalizeAdvisoryAccepted(v) {
  if (!Array.isArray(v) || v.length === 0) return "None";
  const hasApproved = v.some((a) => safeStr(a?.status).toLowerCase() === "approved");
  return hasApproved ? "Yes" : "None";
}

function normalizeApprovedFlag(v) {
  return v === true ? "Yes" : "No";
}

function safeFilenameBase(s) {
  const raw = safeStr(s) || "Website";
  // remove illegal filename chars
  return raw
    .replace(/[\\/:*?"<>|]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80) || "Website";
}

// -------------------- MAIN HANDLER --------------------
export default async function handler(req, res) {
  try {
    if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

    const uid = await getUidFromRequest(req);
    const { websiteId, websiteName, geoMode, locationName } = req.body || {};
    if (!websiteId) return res.status(400).json({ error: "Missing websiteId" });

    const { effectiveUid, effectiveWebsiteId } = await resolveEffectiveContext(uid, websiteId);
    const db = admin.firestore();

    const pageOptimizationRef = db.doc(
      `users/${effectiveUid}/websites/${effectiveWebsiteId}/modules/seo/strategy/pageOptimization`
    );

    const snap = await pageOptimizationRef.get();
    if (!snap.exists) {
      return res.status(400).json({ error: "Missing pageOptimization. Generate Step 7 first." });
    }

    const doc = snap.data() || {};

    // HARD GATE (non-negotiable)
    if (doc.locked !== true) {
      return res.status(400).json({ error: "Step 7 is not locked. Lock Step 7 to enable export." });
    }

    const pagesObj = doc.pages && typeof doc.pages === "object" ? doc.pages : {};

    // -------------------- BUILD EXCEL (AOA) --------------------
    const generatedAt = new Date().toISOString();

    // Row 1 (Header row)
    const row1 = [
      `Generated By: Vyndow SEO Part 2`,
      `Generated At: ${generatedAt}`,
      `Geo Mode: ${safeStr(geoMode)}`,
      `Location: ${safeStr(locationName)}`
    ];

    // Row 2 blank
    const row2 = [];

    // Row 3 table headers (A–M)
    const row3 = [
      "URL",
      "Page Type",
      "Primary Keyword",
      "Secondary Keywords",
      "SEO Title",
      "Meta Description",
      "H1",
      "H2 Structure",
      "Content Blocks",
      "Schema Accepted",
      "Internal Links",
      "Advisory Accepted",
      "Page Approved"
    ];

    const rows = [row1, row2, row3];

    // One row per page
    for (const [pageId, p] of Object.entries(pagesObj)) {
      const page = p || {};
      rows.push([
        safeStr(page.url),
        safeStr(page.pageType),
        safeStr(page.primaryKeyword),
        normalizeSecondaryKeywords(page.secondaryKeywords),
        safeStr(page.title),
        safeStr(page.metaDescription),
        safeStr(page.h1),
        normalizeH2Structure(page.h2Structure),
        normalizeContentBlocks(page.contentBlocks),
        normalizeSchemaAccepted(page.schemaSuggestions),
        normalizeInternalLinks(page.internalLinks),
        normalizeAdvisoryAccepted(page.advisoryBlocks),
        normalizeApprovedFlag(page.approved)
      ]);
    }

    const ws = XLSX.utils.aoa_to_sheet(rows);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "On-Page Blueprint");

    // optional: column widths (safe, no data changes)
    ws["!cols"] = [
      { wch: 45 }, // URL
      { wch: 16 }, // Page Type
      { wch: 24 }, // Primary Keyword
      { wch: 35 }, // Secondary Keywords
      { wch: 35 }, // SEO Title
      { wch: 45 }, // Meta Description
      { wch: 26 }, // H1
      { wch: 40 }, // H2 Structure
      { wch: 55 }, // Content Blocks
      { wch: 22 }, // Schema Accepted
      { wch: 45 }, // Internal Links
      { wch: 18 }, // Advisory Accepted
      { wch: 14 }  // Page Approved
    ];

    const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });

    const base = safeFilenameBase(websiteName);
    const filename = `${base}_OnPage_Blueprint.xlsx`;

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    );
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    return res.status(200).send(buffer);
  } catch (e) {
    console.error("exportPageOptimization error:", e);
    return res.status(500).json({ error: e?.message || "Export failed." });
  }
}
